Oh_My_Nom/Nom/urls.py
from django.conf.urls import url
from Nom import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
    views.show_category, name='show_category'),
]

Oh_My_Nom/Oh_My_Nom/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^Nom/', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^show_recipes/', views.show_recipes, name='show_recipes'),
]

Oh_My_Nom/main/urls.py
from main import views
from django.urls import path
from django.contrib import admin

app_name="main"
urlpatterns = [
	path("",views.index,name="index"),
	#random recipes pages
	path("randomrecipes/",views.randomrecipes,name="randomrecipes"),
	path("myrecipes/",views.myrecipes,name="myrecipes"),
	#restaurants pages
	path("hotrestaurants/",views.hotrestaurants,name="hotrestaurants"),
	path("hotrestaurantclicked/",views.hotrestaurantclicked,name="hotrestaurantclicked"),
	path("myplaces/",views.myplaces,name="myplaces"),
	path("getmyplaces/<int:page>/",views.getmyplaces,name="getmyplaces"),
	path("deletemyplace/",views.deletemyplace,name="deletemyplace"),
	path("getlocation/",views.getlocation,name="getlocation"),
	path("getrestaurants/",views.getrestaurants,name="getrestaurants"),
	#general pages
	path("registersignin/",views.registersignin,name="registersignin"),
	path("signout/",views.signout,name="signout"),
	path("usersettings/",views.usersettings,name="usersettings"),
	path("deleteuser/",views.deleteuser,name="deleteuser"),
	#testing pages
	path("test/",views.test,name="test"),
	path("admin/", admin.site.urls),
	path("recipe/<slug:slug>/",views.show_recipe, name='show_recipe'),
	path("add_rating/",views.add_rating, name='add_rating'),
	path("save_recipe/",views.save_recipe, name="save_recipe"),

]

Oh_My_Nom/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.template.defaultfilters import slugify
from django.utils import timezone


class Recipe(models.Model):
        title = models.CharField(max_length=128, unique=True)
        url = models.URLField()
        slug = models.SlugField(blank=True,null=True)

        def save(self, *args, **kwargs):
                self.slug = slugify(self.title)
                super(Recipe, self).save(*args, **kwargs)

        def __str__(self):
                return self.title



class PageAdmin(admin.ModelAdmin):
	list_display = ('title','url')
	


class SavedRecipe(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + " saves " + self.recipe.title


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(SavedRecipe, on_delete=models.CASCADE)

    date = models.DateTimeField()
    description = models.CharField(max_length=100)
    #dishType = models.CharField(max_length=100)
    #price = models.CharField(max_length=100)
    #fanciness = models.CharField(max_length=100)
    #firstDate = models.CharField(max_length=100)
    #lazyNight = models.CharField(max_length=100)
    #difficulty = models.CharField(max_length=100)
    #dishType = models.CharField(max_length=100)
    #price = models.CharField(max_length=100)
    #veggie = models.CharField(max_length=100)
    overall = models.CharField(max_length=100)
    
    def __str__(self):
        return self.description


class UserInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	location = models.CharField(max_length=128)

	def __str__(self):
		return self.user.username + "; location: "+ self.location

class Restaurant(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	place_id = models.CharField(max_length=200)
	url = models.CharField(max_length=200)
	image_url  = models.CharField(max_length=200)
	name = models.CharField(max_length = 100)
	address = models.CharField(max_length = 250)
	def __str__(self):
		return "User '{}' saved restaurant: {}".format(self.user.username,self.name)

Oh_My_Nom/main/forms.py
from django import forms
from django.contrib.auth.models import User
import datetime
from main.models import Recipe, Rating
from django.contrib.auth.models import User

class RatingForm(forms.ModelForm):
    # user = models.ForeignKey(User)
    # recipe = models.ForeignKey(Recipe)
    date = forms.DateTimeField(widget=forms.HiddenInput(), initial=datetime.time())
    description = forms.CharField(max_length=100,help_text="Enter your rating.")
    #dishType = forms.CharField(max_length=100)
    #price = forms.CharField(max_length=100)
    #fanciness = forms.CharField(max_length=100)
    #firstDate = forms.CharField(max_length=100)
    #lazyNight = forms.CharField(max_length=100)
    #difficulty = forms.CharField(max_length=100)
    #dishType = forms.CharField(max_length=100)
    #price = forms.CharField(max_length=100)
    #veggie = forms.CharField(max_length=100)
    overall = forms.CharField(max_length=100)
    
    
    # an inline class to provide additional information on the form.
    class Meta:
        model = Rating
        # exclude foreign keys
        exclude = ("user", "recipe")

 

Oh_My_Nom/main/views.py
#Http imports
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse, HttpResponseNotFound
import json
#Login and user imports
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from main.models import UserInfo
#Hot restaurants imports
from main.GoogleServices import  GetLocation, GetRestaurantsFromLocation 
from main.models import Restaurant
#Random recipes imports
from main.models import Recipe, SavedRecipe
import random
from main.forms import RatingForm


#Index is the main page of the site
#the html document is stored in the 'templates/main' folder
def index(request):
	return render(request,"main/index.html")


def registersignin(request):
	registered = False
	context_dict={}
	if request.method == 'POST':
		if(request.POST.get("registerusername") and request.POST.get("registerpassword")):
			#This Executes when the register form has been completed
			username = request.POST.get("registerusername")
			password = request.POST.get("registerpassword")
			location = request.POST.get("registerlocation")
			if " " in username:
				print("it's wrong")
				context_dict["register_error"] = "Cannot have a space in username. Try again:"
				return render(request,"main/registersignin.html",context = context_dict)
			try:
				User.objects.get(username=username)
				#The previous statement breaks the code when it cannot find the given user,
				#this code executes when someone tries to reregister a username
				context_dict["register_error"] = "An account with that username already exists"
			except:
				#This code executes when the username provided is new
				user = User(username=username)
				user.save()
				#STILL need to check if password meets minum requirements
				#CHECK IF PASSWORD IS GOOD HERE
				user.set_password(password)
				user.save()
				userInfo = UserInfo(user = user)
				userInfo.save()
				#print("\n\n Successfully saved user\n\n")
				if(location != None):
					userInfo.location = location
					userInfo.save()
				user = authenticate(username=username, password=password)
				if user:
					 if user.is_active:
                                		login(request, user)
                                		return HttpResponseRedirect(reverse('main:index'))

		elif(request.POST.get("signinusername") and request.POST.get("signinpassword")):
			#This code executes when the sign in form has been completed
			username = request.POST.get('signinusername')
			password = request.POST.get('signinpassword')
			user = authenticate(username=username, password=password)
			if user:
				if user.is_active:
					login(request, user)
					return HttpResponseRedirect(reverse('main:index'))
				else:
					context_dict["signin_error"] = "Your account is disabled"
			else:
				#print("Invalid login details: {0}, {1}".format(username, password))
				context_dict["signin_error"] = "Incorrect login details"
		
	return render(request,"main/registersignin.html",context = context_dict)

def signout(request):
	logout(request)
	return HttpResponseRedirect(reverse("main:index"))

def logged_in_or_redirect(view_function):
	def wrapper(*args,**kwargs):
		if not args[0].user.is_authenticated:
			return HttpResponseRedirect(reverse("main:registersignin"))
		return view_function(*args,**kwargs)
	return wrapper

@logged_in_or_redirect
def usersettings(request):
	print("user settings view request")
	if request.method == "POST":
		print("got a post request")
		if(request.POST.get("location")):
			location = request.POST.get("location")
			print("got new location", location)
			userinfo = UserInfo.objects.get_or_create(user = request.user)[0]
			print(type(userinfo))
			userinfo.location = location
			userinfo.save()
			print("location saved !")

	return render(request,"main/usersettings.html")


def deleteuser(request):
	if request.method == "POST":
		if request.user.is_authenticated:
			user = request.user
			logout(request)
			user.delete()
			print("user deleted")
	return HttpResponseRedirect(reverse("main:index"))

def getlocation(request):
	#get location stuff here
	return JsonResponse(GetLocation(request))
	
def getrestaurants(request):
	if request.method == "POST":
		try:
			json_dict = json.loads(request.body.decode('utf-8'))
		except:
			return JsonResponse({"error":"poor request"})

		if("location" not in json_dict):
			return JsonResponse({"error":"no location associated to request"})
		location = json_dict["location"]
		restaurants = GetRestaurantsFromLocation(location = location)
		status = "ok" if (len(restaurants) > 0) else "not ok"
		return JsonResponse({"restaurants":restaurants,"status":status})

	return JsonResponse({"error":"incorrect request type, please use post..."})

def hotrestaurants(request):
	return render(request,"main/hotrestaurants.html")

def hotrestaurantclicked(request):
	if request.method == "POST":
		try:
			json_dict = json.loads(request.body.decode('utf-8'))
		except:
			return JsonResponse({"status":"not ok","error":"bad json request"})
		if("restaurant" not in json_dict):
			return JsonResponse({"status":"not ok","error":"missing parameters"})
		necessary_elements = ["place_id","image_url","name","address","google_url"]
		if not all (element in necessary_elements for element in json_dict["restaurant"]):
			return JsonResponse({"status":"not ok","error":"missing parameters"})
		if(request.user.is_authenticated):
			restaurant = Restaurant.objects.get_or_create(user = request.user,place_id=json_dict["restaurant"]["place_id"])[0]
			restaurant.place_id = json_dict["restaurant"]["place_id"]
			restaurant.image_url = json_dict["restaurant"]["image_url"]
			restaurant.url = json_dict["restaurant"]["google_url"]
			restaurant.name = json_dict["restaurant"]["name"]
			restaurant.address = json_dict["restaurant"]["address"]
			restaurant.save()
			return JsonResponse({"status":"ok"})
		return JsonResponse({"status":"not ok","error":"user not logged in"})
	else:
		return JsonResponse({"status":"not ok","error":"incorrect request type"})



@logged_in_or_redirect	
def myplaces(request):
	return render(request,"main/myplaces.html")


def getmyplaces(request,page):
	if(request.user.is_authenticated):
		if(request.method == "GET"):
			if(page >= 0):
				restaurants_per_page = 1
				all_restaurants = Restaurant.objects.filter(user = request.user)
				if(len(all_restaurants) == 0):
					return JsonResponse({"restaurants":[], "status":"ok","message":"You don't have any saved restaurants!"})
				restaurants = []
				for i in range(page*restaurants_per_page,(page+1)*restaurants_per_page):
					if(i >= len(all_restaurants)):
						break
					restaurant = {"place_id":all_restaurants[i].place_id,"google_url":all_restaurants[i].url,"address":all_restaurants[i].address,"image_url":all_restaurants[i].image_url,"name":all_restaurants[i].name}
					restaurants.append(restaurant)
				return JsonResponse({"restaurants":restaurants,"status":("ok" if len(restaurants) > 0 else "not ok")})
													
	return JsonResponse({"error":"unacceptable request","status":"not ok"})

def deletemyplace(request):
	if(request.user.is_authenticated):
		if(request.method == "POST"):
			try:
				json_dict = json.loads(request.body.decode('utf-8'))
			except:
				return JsonResponse({"error":"bad json","status":"not ok"})
			if("place_id" not in json_dict):
				return JsonResponse({"error":"incomplete json","status":"not ok"})
			to_delete = Restaurant.objects.filter(user = request.user, place_id = json_dict["place_id"])
			to_delete.delete()
			return JsonResponse({"status":"ok","message":"restaurant removed from favourites"})
	return JsonResponse({"status":"not ok","error":"incorrect request mecanism"})
			
def randomrecipes(request):
		recipes = []
		names = []
		count = 0
		
		#get random numbers and pick those indices as recipes (range of how many recipes you have)
		randList = random.sample(range(0,19),5)

		for r in Recipe.objects.all():
			if (count in randList):
				name = r.title
				slug = r.slug
				url = r.url
				recipes += [(slug,name)]
			count += 1
				
		return render(request,"main/randomrecipes.html",{"recipes":recipes})

@logged_in_or_redirect
def myrecipes(request):
	user = None
	myrecipes = []
	user = request.user
	
	for recipe in SavedRecipe.objects.all():
		rList = str(recipe).split(" ")
		rec = rList[2:]
		strR = ""
		for el in rec:
			strR = strR +" " + el
		result = strR[1:]
		for original in Recipe.objects.all():
			if (result == original.title):
				if recipe.user == user:
					name = original.title
					slug = original.slug
					myrecipes += [(slug,name)]
	return render(request, 'main/myrecipes.html', {"myrecipes":myrecipes})

def test(request):
	return render(request,"main/test.html")

@logged_in_or_redirect
def save_recipe(request):
	context_dict = {}
	print("OMG")
	if request.method == "POST":
		print("Got a post request")
		recipe_title =  request.POST.get('recipe_title')
		print(recipe_title)
		if (recipe_title==None):
			print("recipe not found... this shouldnt happen")
			return HttpResponseNotFound("Go back")
			
		recipe = get_object_or_404(Recipe,title=recipe_title)
		print("Got da sweet recipe, gonna save it to the database")
		s = SavedRecipe.objects.get_or_create(recipe=recipe,user=request.user)[0]
		print("saving recipe object: ",s)
		s.save()
		print("saved the recipe, WELL DONE!")
		context_dict["recipe"] = recipe
		context_dict["message"] = "Recipe saved!"
		return render(request, "main/recipe.html", context_dict)
	else:
		print("ERROR!")
		return HttpResponse("")


def show_recipe(request, slug):
        context_dict = {}
        try:
                recipe = Recipe.objects.get(slug=slug)
                context_dict["recipe"] = recipe
        except Recipe.DoesNotExist:
                context_dict["recipe"] = None
        return render(request, 'main/recipe.html', context_dict)

Oh_My_Nom/templates/main/base.html
<!DOCTYPE html>
{% load staticfiles %}
	<html>
		<head lang="en">
			<link rel="shortcut icon" href="{% static 'favicon/favicon.png' %}"/>
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
			<title>
				{% block title %}Oh My Nom!{% endblock %}
			</title>
			<!-- Bootstrap core CSS -->
			<link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
			<!-- Custom styles for this template -->
			<link href="{% static 'css/base.css' %}" rel="stylesheet">
			<link href= "http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
		</head>
		<body>
			<div class="masthead clearfix">
				<nav class="nav nav-masthead">
					<a class="nav-link active" href="{% url 'main:index' %}">Home</a>
					<a class="nav-link" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Contact Us</a>
					{% if user.is_authenticated %}
						<a class="nav-link" href="{% url 'main:usersettings' %}">Settings: {{ user.username }}</a>
						<a class="nav-link" href="{% url 'main:signout' %}">Logout</a>
					{% else %}
						<a class="nav-link" href="{% url 'main:registersignin' %}">Register/Sign in</a>
					{% endif %}
				</nav>
			</div>
			<h1 class="cover-heading">Oh My Nom!</h1>


			{% block main_block %}
			{% endblock%}
		</body>
		<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
		<script type="text/javascript" src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="{% static "js/base.js" %}"></script>
	</html>

Oh_My_Nom/templates/main/hotrestaurants.html
{% extends 'main/base.html' %}
{% load staticfiles %}

<!-- Should Only be seen if user is logged in -->
{% block main_block %}
	<link href="{% static 'css/hotrestaurants.css' %}" rel="stylesheet">
	
	<a id="top_link" href="{% url 'main:myplaces' %}">Saved Places</a>
	<a id="top_link" href="{% url 'main:hotrestaurants' %}">Random Restaurants</a>
	<br>	
	<br>
	<p id="location_message" style="white-space: pre-line"></p>

	{% csrf_token %}
	Optimize your location: <input id="location_text" type="text" name="location" value="" size="10" />
	<button class="btn btn-secondary" onclick="UpdateLocation()">Update Location</button>
	<br>
	
	<div id="restaurant">
	<strong><a href="#" onclick="RestaurantClicked();return false;" id="restaurant_name"></a></strong>
	<button id="save_restaurant" class="btn btn-secondary" onclick="SaveRestaurant()">Save Restaurant</button>
	<br>	
	<div id="saved_restaurant"></div>
	<img id="restaurant_image" src="">	
	<br>
	<strong><p id="restaurant_address"></p></strong>	
	</div>

	<button id="next_restaurant" class="btn btn-secondary" onclick="NextRestaurant()">Give Me Another Restaurant!</button>

	<script type="text/javascript" src="{% static "js/hotrestaurants.js" %}"></script>

{% endblock %}

Oh_My_Nom/templates/main/index.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block main_block %}
	<div class="inner cover">
        <p>Feed me I'm bored!</p>
        <p class="lead">
        <a href="{% url 'main:hotrestaurants' %}" class="btn btn-lg btn-secondary">Take Me Out!</a>
	<a href="{% url 'main:randomrecipes' %}" class="btn btn-lg btn-secondary">Generate Random Recipes</a>
        </p>
	</div>

{% endblock %}

Oh_My_Nom/templates/main/myplaces.html
{% extends 'main/base.html' %}
{% load staticfiles %}

<!-- Should Only be seen if user is logged in -->
{% block main_block %}
	<link rel="stylesheet" type="text/css" href="{% static "css/myplaces.css" %}"> 
	<a id="top_link" href="{% url 'main:myplaces' %}">Saved Places</a>
	<a id="top_link" href="{% url 'main:hotrestaurants' %}">Random Restaurants</a>
	{% csrf_token %}
	<div id="restaurants_container">
	</div>		
	<button class="btn btn-secondary" id="previous_page" onclick="PrevPage();">Previous Page</button>
	<button class="btn btn-secondary" id="next_page" onclick="NextPage();">Next Page</button>

	<script src="{% static "js/myplaces.js" %}"></script>
{% endblock %}

Oh_My_Nom/templates/main/myrecipes.html
{% extends 'main/base.html' %}
{% load staticfiles %}

<!-- Should Only be seen if user is logged in -->
{% block main_block %}
	<h2> Welcome to your saved recipes: </h2>
	<!-- Displays all the users saved recipes when they are logged in --> 
	<div class = "recipes">
		{% for slug,name in myrecipes %}
			<li><a id='recipe' href="/recipe/{{ slug }}">{{ name }}</a></li>
		{% endfor %}
	</div>
	<br>
		<!-- Also gives the user the option to generate another random recipe --> 
        <a href="{% url 'main:randomrecipes' %}" class="btn btn-lg btn-secondary">Give me more recipes!</a>
{% endblock %}

	<script src="{% static "js/click.js" %}"></script>
	<script type="text/javascript">
	</script>

Oh_My_Nom/templates/main/randomrecipes.html
{% extends 'main/base.html' %}
{% load staticfiles %}

<!-- Should Only be seen if user is logged in -->
{% block main_block %}
	<script type="text/javascript" src="{% static "js/main-ajax.js" %}"></script>
	<script type="text/javascript">
	</script>
	
	<h2>Your random recipes are:</h2> 
	<div class = "recipes">
	<p class = "p1">
		{% for slug,name in recipes %}
			<li><a id='recipe' href="/recipe/{{ slug }}">{{ name }}</a></li>
		{% endfor %}
		</p>
	</div>
	<br>
	
	
        <a href="{% url 'main:myrecipes' %}" class="btn btn-lg btn-secondary">My Recipes</a>
		<a href="{% url 'main:randomrecipes' %}" class="btn btn-lg btn-secondary">Generate Random Recipes</a>
{% endblock %}

Oh_My_Nom/templates/main/recipe.html
{% extends "main/base.html" %}
{% load staticfiles %}
	<script type="text/javascript" src="{% static '/js/click.js' %}"></script>
	<!-- Displays the title and url of the selected recipe along with the buttons Save Recipe to save it and Generate Random Recipes to randomise more recipes -->
{% block main_block %}
	<div>
	{% if recipe %}
		<h1>{{ recipe.title }}</h1>
		<div>
		<a href={{ recipe.url}} class = "link" >Link to the recipe website</a>
			<form id="location_form" method="post" action="{% url 'main:save_recipe' %}"enctype="multipart/form-data">
					{% csrf_token %}
					<input id="recipe_title" name="recipe_title" type="hidden" value="{{ recipe.title }}">
                	<input type="submit" name="submit" class="btn btn-lg btn-secondary" value="Save Recipe!"/>
        	</form>
		</div>
		{% if message %}
			<div> {{ message }} </div>
		{% endif %}
		<hr>
		<a href="{% url 'main:randomrecipes' %}" class="btn btn-lg btn-secondary">Generate Random Recipes</a>
	{% else %}
		The specified recipe does not exist!
	{% endif %}
	</div>
{% endblock %}

Oh_My_Nom/templates/main/registersignin.html
{% extends 'main/base.html' %}
{% load staticfiles %}
<!-- Gives the user the option to enter in their details to either sign in or register for Oh My Nom! --> 
{% block main_block %}
	<h2>Register Here:</h2>
	{% if register_error %}
		<p>{{ register_error }}<p/>
	{% endif %}
	<form id="user_form" method="post" action="{% url 'main:registersignin' %}"enctype="multipart/form-data">
		{% csrf_token %}
		Username: <input type="text" name="registerusername" value="" size="50" />
		<br />
		Password: <input type="password" name="registerpassword" value="" size="50" />
		<br />	
		Approximate location: <input type="text" name="registerlocation" value="" size="50" />
		<br />	
		<input type="submit" name="submit" class="btn btn-lg btn-secondary" value="Register" />
	</form>
	<br />
	<br />
	<h2>Or Sign In!</h2>
	{% if signin_error %}
		<p>{{ signin_error }}<p/>
	{% endif %}
	<form id="login_form" method="post" action="{% url 'main:registersignin' %}">
		{% csrf_token %}
		Username: <input type="text" name="signinusername" value="" size="50" />
		<br />
		Password: <input type="password" name="signinpassword" value="" size="50" />
		<br />
		<input type="submit" class="btn btn-lg btn-secondary" value="Sign In" />
	</form>

{% endblock %} 

Oh_My_Nom/templates/main/test.html
<!DOCTYPE html>

{% load staticfiles %}


<html>
<body>

<h2>THIS IS A TEST</h2>
<p>The Test Was Successful! Templates Are Served!</p>

<img src="{% static "images/test.jpg" %}" alt="This Picture should have loaded, maybe static files aren't served though" />
</body>
</html>

Oh_My_Nom/templates/main/usersettings.html
{% extends 'main/base.html' %}
{% load staticfiles %}

<!-- Should Only be seen if user is logged in -->
{% block main_block %}
	<form id="Location_form" method="post" action="{% url 'main:usersettings' %}"enctype="multipart/form-data">
		{% csrf_token %}
		<p>Current location is: {{ user.userinfo.location }}</p>
		Change location: <input type="text" name="location" value="{{ user.userinfo.location }}" size="50" />
		<br />
		<input type="submit" name="submit" class="btn btn-lg btn-secondary" value="Change location" />
	</form>
	
	<form id="Location_form" method="post" action="{% url 'main:deleteuser' %}"enctype="multipart/form-data">
		{% csrf_token %}
		<input type="submit" name="submit" class="btn btn-lg btn-secondary" value="Delete Account" />
{% endblock %}